packages:
  - 'config/*'
  - 'docs/*'
  - 'packages/*'

catalog:
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.2
  '@vitejs/plugin-react': ^4.4.1
  '@vitejs/plugin-vue': ^5.2.3
  '@types/node': ^24.0.3
  '@tarojs/components': 4.1.2
  '@tarojs/taro': 4.1.2
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ^5.8.3
  vite: ^6.3.5
  vue: ^3.5.16
